app = "animebot72" 
primary_region = "gru" 
 
[build] 
  dockerfile = "Dockerfile" 
 
[env] 
  NODE_OPTIONS = "--max-old-space-size=6144" 
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true" 
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable" 
 
[http_service] 
  internal_port = 3000 
  force_https = true 
  auto_stop_machines = false 
  auto_start_machines = true 
 
[[services]] 
  protocol = "tcp" 
  internal_port = 6080 
 
  [[services.ports]] 
    port = 8080 
    handlers = ["http"] 
 
[[mounts]] 
  source = "yakabot_data" 
  destination = "/app/data" 
 
